/**
 * Copyright (c) 2020 Christian Schärf
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BASISSET_HPP
#define BASISSET_HPP

// STO-3G basis set
// Data taken from http://basissetexchange.org
const std::string basisset_file("{\n"
                                "    \"molssi_bse_schema\": {\n"
                                "        \"schema_type\": \"complete\",\n"
                                "        \"schema_version\": \"0.1\"\n"
                                "    },\n"
                                "    \"revision_description\": \"Data from Gaussian09\",\n"
                                "    \"revision_date\": \"2018-06-19\",\n"
                                "    \"elements\": {\n"
                                "        \"1\": {\n"
                                "            \"electron_shells\": [\n"
                                "                {\n"
                                "                    \"function_type\": \"gto\",\n"
                                "                    \"region\": \"\",\n"
                                "                    \"angular_momentum\": [\n"
                                "                        0\n"
                                "                    ],\n"
                                "                    \"exponents\": [\n"
                                "                        \"0.3425250914E+01\",\n"
                                "                        \"0.6239137298E+00\",\n"
                                "                        \"0.1688554040E+00\"\n"
                                "                    ],\n"
                                "                    \"coefficients\": [\n"
                                "                        [\n"
                                "                            \"0.1543289673E+00\",\n"
                                "                            \"0.5353281423E+00\",\n"
                                "                            \"0.4446345422E+00\"\n"
                                "                        ]\n"
                                "                    ]\n"
                                "                }\n"
                                "            ],\n"
                                "            \"references\": [\n"
                                "                {\n"
                                "                    \"reference_description\": \"STO-3G Minimal Basis (3 functions/AO)\",\n"
                                "                    \"reference_keys\": [\n"
                                "                        \"hehre1969a\"\n"
                                "                    ]\n"
                                "                }\n"
                                "            ]\n"
                                "        },\n"
                                "        \"6\": {\n"
                                "            \"electron_shells\": [\n"
                                "                {\n"
                                "                    \"function_type\": \"gto\",\n"
                                "                    \"region\": \"\",\n"
                                "                    \"angular_momentum\": [\n"
                                "                        0\n"
                                "                    ],\n"
                                "                    \"exponents\": [\n"
                                "                        \"0.7161683735E+02\",\n"
                                "                        \"0.1304509632E+02\",\n"
                                "                        \"0.3530512160E+01\"\n"
                                "                    ],\n"
                                "                    \"coefficients\": [\n"
                                "                        [\n"
                                "                            \"0.1543289673E+00\",\n"
                                "                            \"0.5353281423E+00\",\n"
                                "                            \"0.4446345422E+00\"\n"
                                "                        ]\n"
                                "                    ]\n"
                                "                },\n"
                                "                {\n"
                                "                    \"function_type\": \"gto\",\n"
                                "                    \"region\": \"\",\n"
                                "                    \"angular_momentum\": [\n"
                                "                        0,\n"
                                "                        1\n"
                                "                    ],\n"
                                "                    \"exponents\": [\n"
                                "                        \"0.2941249355E+01\",\n"
                                "                        \"0.6834830964E+00\",\n"
                                "                        \"0.2222899159E+00\"\n"
                                "                    ],\n"
                                "                    \"coefficients\": [\n"
                                "                        [\n"
                                "                            \"-0.9996722919E-01\",\n"
                                "                            \"0.3995128261E+00\",\n"
                                "                            \"0.7001154689E+00\"\n"
                                "                        ],\n"
                                "                        [\n"
                                "                            \"0.1559162750E+00\",\n"
                                "                            \"0.6076837186E+00\",\n"
                                "                            \"0.3919573931E+00\"\n"
                                "                        ]\n"
                                "                    ]\n"
                                "                }\n"
                                "            ],\n"
                                "            \"references\": [\n"
                                "                {\n"
                                "                    \"reference_description\": \"STO-3G Minimal Basis (3 functions/AO)\",\n"
                                "                    \"reference_keys\": [\n"
                                "                        \"hehre1969a\"\n"
                                "                    ]\n"
                                "                }\n"
                                "            ]\n"
                                "        },\n"
                                "        \"8\": {\n"
                                "            \"electron_shells\": [\n"
                                "                {\n"
                                "                    \"function_type\": \"gto\",\n"
                                "                    \"region\": \"\",\n"
                                "                    \"angular_momentum\": [\n"
                                "                        0\n"
                                "                    ],\n"
                                "                    \"exponents\": [\n"
                                "                        \"0.1307093214E+03\",\n"
                                "                        \"0.2380886605E+02\",\n"
                                "                        \"0.6443608313E+01\"\n"
                                "                    ],\n"
                                "                    \"coefficients\": [\n"
                                "                        [\n"
                                "                            \"0.1543289673E+00\",\n"
                                "                            \"0.5353281423E+00\",\n"
                                "                            \"0.4446345422E+00\"\n"
                                "                        ]\n"
                                "                    ]\n"
                                "                },\n"
                                "                {\n"
                                "                    \"function_type\": \"gto\",\n"
                                "                    \"region\": \"\",\n"
                                "                    \"angular_momentum\": [\n"
                                "                        0,\n"
                                "                        1\n"
                                "                    ],\n"
                                "                    \"exponents\": [\n"
                                "                        \"0.5033151319E+01\",\n"
                                "                        \"0.1169596125E+01\",\n"
                                "                        \"0.3803889600E+00\"\n"
                                "                    ],\n"
                                "                    \"coefficients\": [\n"
                                "                        [\n"
                                "                            \"-0.9996722919E-01\",\n"
                                "                            \"0.3995128261E+00\",\n"
                                "                            \"0.7001154689E+00\"\n"
                                "                        ],\n"
                                "                        [\n"
                                "                            \"0.1559162750E+00\",\n"
                                "                            \"0.6076837186E+00\",\n"
                                "                            \"0.3919573931E+00\"\n"
                                "                        ]\n"
                                "                    ]\n"
                                "                }\n"
                                "            ],\n"
                                "            \"references\": [\n"
                                "                {\n"
                                "                    \"reference_description\": \"STO-3G Minimal Basis (3 functions/AO)\",\n"
                                "                    \"reference_keys\": [\n"
                                "                        \"hehre1969a\"\n"
                                "                    ]\n"
                                "                }\n"
                                "            ]\n"
                                "        },\n"
                                "        \"21\": {\n"
                                "            \"electron_shells\": [\n"
                                "                {\n"
                                "                    \"function_type\": \"gto\",\n"
                                "                    \"region\": \"\",\n"
                                "                    \"angular_momentum\": [\n"
                                "                        0\n"
                                "                    ],\n"
                                "                    \"exponents\": [\n"
                                "                        \"0.9416624250E+03\",\n"
                                "                        \"0.1715249862E+03\",\n"
                                "                        \"0.4642135516E+02\"\n"
                                "                    ],\n"
                                "                    \"coefficients\": [\n"
                                "                        [\n"
                                "                            \"0.1543289673E+00\",\n"
                                "                            \"0.5353281423E+00\",\n"
                                "                            \"0.4446345422E+00\"\n"
                                "                        ]\n"
                                "                    ]\n"
                                "                },\n"
                                "                {\n"
                                "                    \"function_type\": \"gto\",\n"
                                "                    \"region\": \"\",\n"
                                "                    \"angular_momentum\": [\n"
                                "                        0,\n"
                                "                        1\n"
                                "                    ],\n"
                                "                    \"exponents\": [\n"
                                "                        \"0.6717668771E+02\",\n"
                                "                        \"0.1561041754E+02\",\n"
                                "                        \"0.5076992278E+01\"\n"
                                "                    ],\n"
                                "                    \"coefficients\": [\n"
                                "                        [\n"
                                "                            \"-0.9996722919E-01\",\n"
                                "                            \"0.3995128261E+00\",\n"
                                "                            \"0.7001154689E+00\"\n"
                                "                        ],\n"
                                "                        [\n"
                                "                            \"0.1559162750E+00\",\n"
                                "                            \"0.6076837186E+00\",\n"
                                "                            \"0.3919573931E+00\"\n"
                                "                        ]\n"
                                "                    ]\n"
                                "                },\n"
                                "                {\n"
                                "                    \"function_type\": \"gto\",\n"
                                "                    \"region\": \"\",\n"
                                "                    \"angular_momentum\": [\n"
                                "                        0,\n"
                                "                        1\n"
                                "                    ],\n"
                                "                    \"exponents\": [\n"
                                "                        \"0.4698159231E+01\",\n"
                                "                        \"0.1433088313E+01\",\n"
                                "                        \"0.5529300235E+00\"\n"
                                "                    ],\n"
                                "                    \"coefficients\": [\n"
                                "                        [\n"
                                "                            \"-0.2277635023E+00\",\n"
                                "                            \"0.2175436044E+00\",\n"
                                "                            \"0.9166769611E+00\"\n"
                                "                        ],\n"
                                "                        [\n"
                                "                            \"0.4951511155E-02\",\n"
                                "                            \"0.5777664691E+00\",\n"
                                "                            \"0.4846460366E+00\"\n"
                                "                        ]\n"
                                "                    ]\n"
                                "                },\n"
                                "                {\n"
                                "                    \"function_type\": \"gto\",\n"
                                "                    \"region\": \"\",\n"
                                "                    \"angular_momentum\": [\n"
                                "                        0,\n"
                                "                        1\n"
                                "                    ],\n"
                                "                    \"exponents\": [\n"
                                "                        \"0.6309328384E+00\",\n"
                                "                        \"0.2328538976E+00\",\n"
                                "                        \"0.1028307363E+00\"\n"
                                "                    ],\n"
                                "                    \"coefficients\": [\n"
                                "                        [\n"
                                "                            \"-0.3088441214E+00\",\n"
                                "                            \"0.1960641165E-01\",\n"
                                "                            \"0.1131034442E+01\"\n"
                                "                        ],\n"
                                "                        [\n"
                                "                            \"-0.1215468600E+00\",\n"
                                "                            \"0.5715227604E+00\",\n"
                                "                            \"0.5498949471E+00\"\n"
                                "                        ]\n"
                                "                    ]\n"
                                "                },\n"
                                "                {\n"
                                "                    \"function_type\": \"gto_spherical\",\n"
                                "                    \"region\": \"\",\n"
                                "                    \"angular_momentum\": [\n"
                                "                        2\n"
                                "                    ],\n"
                                "                    \"exponents\": [\n"
                                "                        \"0.5517000679E+00\",\n"
                                "                        \"0.1682861055E+00\",\n"
                                "                        \"0.6493001120E-01\"\n"
                                "                    ],\n"
                                "                    \"coefficients\": [\n"
                                "                        [\n"
                                "                            \"0.2197679508E+00\",\n"
                                "                            \"0.6555473627E+00\",\n"
                                "                            \"0.2865732590E+00\"\n"
                                "                        ]\n"
                                "                    ]\n"
                                "                }\n"
                                "            ],\n"
                                "            \"references\": [\n"
                                "                {\n"
                                "                    \"reference_description\": \"STO-3G Minimal Basis (3 functions/AO)\",\n"
                                "                    \"reference_keys\": [\n"
                                "                        \"pietro1983a\"\n"
                                "                    ]\n"
                                "                }\n"
                                "            ]\n"
                                "        }\n"
                                "    },\n"
                                "    \"version\": \"1\",\n"
                                "    \"function_types\": [\n"
                                "        \"gto\",\n"
                                "        \"gto_spherical\"\n"
                                "    ],\n"
                                "    \"names\": [\n"
                                "        \"STO-3G\"\n"
                                "    ],\n"
                                "    \"tags\": [],\n"
                                "    \"family\": \"sto\",\n"
                                "    \"description\": \"STO-3G Minimal Basis (3 functions/AO)\",\n"
                                "    \"role\": \"orbital\",\n"
                                "    \"auxiliaries\": {},\n"
                                "    \"name\": \"STO-3G\"\n"
                                "}");

#endif //BASISSET_HPP
