language: cpp
dist: bionic
compiler:
  - gcc
  - clang
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug .
  - make -j $(nproc)
addons:
  apt:
    packages:
      - libboost-container-dev
      - libeigen3-dev
      - libfmt-dev
      - nlohmann-json-dev
