version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build_gcc:
    docker:
      - image: 'ubuntu:focal'
    environment:
      - DEBIAN_FRONTEND: noninteractive
      - CC: gcc-10
      - CXX: g++-10
      - CXXFLAGS: -Werror
    steps:
      - run: apt-get update && apt-get install --no-install-recommends -y cmake g++-10 git googletest libboost-container-dev libboost-program-options-dev libeigen3-dev libfmt-dev ninja-build nlohmann-json3-dev
      - checkout
      - run: cmake . -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - run: ninja -v
      - run: ctest

  build_clang:
    docker:
      - image: 'ubuntu:focal'
    environment:
      - DEBIAN_FRONTEND: noninteractive
      - CC: clang-10
      - CXX: clang++-10
      - CXXFLAGS: -Werror
    steps:
      - run: apt-get update && apt-get install --no-install-recommends -y clang-10 cmake curl git googletest libboost-container-dev libboost-program-options-dev libeigen3-dev libfmt-dev libstdc++-10-dev ninja-build nlohmann-json3-dev
      - checkout
      - run: cmake . -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - run: ninja -v
      - run: ctest

  build_coverage:
    docker:
      - image: 'ubuntu:focal'
    environment:
      - DEBIAN_FRONTEND: noninteractive
      - CC: gcc-10
      - CXX: g++-10
      - CXXFLAGS: -Werror --coverage
      - LDFLAGS: --coverage
    steps:
      - run: apt-get update && apt-get install --no-install-recommends -y cmake g++-10 git googletest lcov libboost-container-dev libboost-program-options-dev libeigen3-dev libfmt-dev ninja-build nlohmann-json3-dev
      - checkout
      - run: cmake . -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - run: ninja -v
      - run: ctest
      - run: lcov -c -d CMakeFiles/fastboys_common.dir/src -o coverage.info
      - codecov/upload:
          file: coverage.info

workflows:
  version: 2.1
  build_all:
    jobs:
      - build_gcc
      - build_clang
      - build_coverage
